export const ABBREVIATIONS: Record<string, string> = {
  'P/E': 'Precio / Beneficio: cuánto pagas por cada $1 de beneficio. Bajo = barato; alto = expectativas de crecimiento.',
  'P/B': 'Precio / Valor en libros: compara el precio con el patrimonio neto por acción. 1x = compras a precio de libros.',
  'P/S': 'Precio / Ventas: cuánto paga el mercado por cada $1 de ingresos. Útil para empresas sin beneficios.',
  'EV': 'Enterprise Value (valor de empresa): capitalización bursátil + deuda neta. Valor total de la empresa.',
  'EV/EBITDA': 'Valor de empresa / beneficio operativo antes de amortizaciones. Menor = potencialmente más barato.',
  'EV/EBIT': 'Valor de empresa / beneficio operativo. Más conservador que EV/EBITDA porque no suma la depreciación.',
  'ROE': 'Retorno sobre el patrimonio: beneficio neto / capital de los accionistas. Mide la rentabilidad para el accionista.',
  'ROA': 'Retorno sobre los activos: beneficio neto / activos totales. Mide cuán eficiente es la empresa usando sus activos.',
  'ROIC': 'Retorno sobre el capital invertido: beneficio operativo / capital invertido. Mide si la empresa crea valor al reinvertir.',
  'Current Ratio': 'Ratio de liquidez: activos corrientes / pasivos corrientes. Mide si puede pagar sus deudas a corto plazo.',
  'Debt/Equity': 'Deuda / Patrimonio: apalancamiento. Alto = depende más de deuda para financiarse.',
  'Dividend Yield': 'Rendimiento por dividendo: dividendo anual / precio de la acción. Lo que te paga la empresa por tenerla.',
  'Altman Z-Score': 'Indicador de riesgo de quiebra. Z > 3 = sana; Z < 1.8 = riesgo elevado de bancarrota.',
  'Piotroski': 'Puntuación de fortaleza financiera (0-9). Suma señales de rentabilidad, apalancamiento y eficiencia.',
  'DCF': 'Flujo de Caja Descontado: estima el valor proyectando los flujos de caja futuros y descontándolos al presente.',
  'PER': 'Precio / Beneficio (P/E). Cuánto pagas por cada unidad de beneficio. Método más usado por inversores.',
  'DDM': 'Descuento de Dividendos: valora la acción como la suma de sus dividendos futuros descontados.',
  'FCF Yield': 'Flujo de caja libre como % del precio de mercado. Mayor = genera más efectivo relativo a su precio.',
  'NCAV': 'Net Current Asset Value: activos corrientes ajustados menos deuda. Valor de liquidación de Graham.',
  'Graham': 'Número de Graham: tope defensivo de precio basado en beneficio y patrimonio. Por debajo = ganga segura.',
  'EBIT': 'Beneficio antes de intereses e impuestos. Mide el resultado de la operación pura.',
  'EBITDA': 'Beneficio antes de intereses, impuestos, depreciación y amortización. Mide la generación operativa de caja.',
  'EPS': 'Earnings Per Share: beneficio neto dividido entre las acciones. Beneficio por acción.',
  'BVPS': 'Book Value Per Share: patrimonio neto dividido entre las acciones. Valor contable por acción.',
  'FCF': 'Free Cash Flow: efectivo generado después de pagar gastos e inversión (CapEx). Caja realmente libre.',
  'CapEx': 'Capital Expenditures: inversión en activos fijos (fábricas, equipos, tecnología). Reinversión para crecer. Como intensidad: CapEx ÷ ingresos.',
  'SGA': 'Selling, General & Administrative: gastos comerciales y administrativos.',
  'I+D': 'Investigación y Desarrollo: gasto en innovación de productos y tecnología.',
  'COGS': 'Cost of Goods Sold: costo directo de producir los bienes o servicios vendidos.',
  'Goodwill': 'Fondo de comercio: prima pagada al comprar otra empresa por encima del valor de sus activos.',
  'Market Cap': 'Capitalización bursátil: precio de la acción × acciones en circulación. Valor de mercado de la empresa.',
  'TTM': 'Trailing Twelve Months: últimos 12 meses acumulados. Suma de los 4 trimestres más recientes.',
  'Rev YoY': 'Crecimiento de ingresos año contra año: % de aumento/disminución de la cifra de ventas respecto al ejercicio anterior.',
  'NI YoY': 'Crecimiento del beneficio neto año contra año: % de variación del resultado final respecto al ejercicio anterior.',
  'FCF YoY': 'Crecimiento del flujo de caja libre año contra año: variación de la caja generada tras inversiones (CapEx).',
  'CAGR 3A': 'CAGR a 3 años: tasa de crecimiento anual compuesta de los ingresos en los últimos 3 ejercicios.',
  'CAGR 5A': 'CAGR a 5 años: tasa de crecimiento anual compuesta de los ingresos en los últimos 5 ejercicios.',
  'CAGR NI 5A': 'CAGR del beneficio neto a 5 años: tasa de crecimiento anual compuesta del resultado en los últimos 5 ejercicios.',
  'PEG': 'Precio/Beneficio ajustado por crecimiento: P/E ÷ crecimiento esperado. PEG < 1 = barato para su crecimiento; PEG > 2 = caro.',
  'G. Sostenible': 'Crecimiento sostenible: tasa máxima a la que la empresa puede crecer sin deuda adicional = ROE × tasa de retención (beneficios no repartidos como dividendos ni recompras).',
  'Deuda neta': 'Deuda total (corto + largo plazo) menos caja e inversiones a corto. Deuda neta negativa = posición de caja neta.',
  'ND/EBITDA': 'Deuda neta / EBITDA: años que tardaría en pagar la deuda con el beneficio operativo. < 2 sano; > 4 puede ser riesgoso.',
  'Cob. Interés': 'Cobertura de intereses: EBIT ÷ gastos por intereses. Indica cuántas veces el beneficio operativo cubre los intereses. > 3 seguro.',
  'Quick ratio': 'Ratio rápido: (activo corriente - inventario) ÷ pasivo corriente. Mide liquidez sin depender de vender inventario. > 1 recomendable.',
  'Capital circ.': 'Capital circulante (working capital): activo corriente - pasivo corriente. Positivo = liquidez para el ciclo operativo.',
  'Payout': 'Payout ratio: dividendos ÷ beneficio neto. % del beneficio que se reparte como dividendo. > 90% puede no ser sostenible.',
  'Cob. Div.': 'Cobertura de dividendo: beneficio neto ÷ dividendos. Cuántas veces cubre el beneficio el dividendo. > 1.5 cómodo.',
  'Buyback': 'Buyback yield: recompras de acciones ÷ capitalización bursátil. % del valor devuelto al accionista vía recompra.',
  'Sh. Yield': 'Shareholder yield: (dividendos + recompras) ÷ capitalización. Retorno total devuelto al accionista.',
  'Div/FCF': 'Dividendos ÷ flujo de caja libre. Cuántas veces cubre el FCF el dividendo; > 1 implica que se paga con caja generada.',
  'Margen neto': 'Beneficio neto ÷ ingresos. % de cada venta que queda como beneficio final.',
  'Margen bruto': 'Beneficio bruto ÷ ingresos. % que queda tras el costo directo de producción (COGS).',
  'Margen op.': 'Margen operativo: EBIT ÷ ingresos. Rentabilidad de la operación antes de intereses e impuestos.',
  'Margen FCF': 'Flujo de caja libre ÷ ingresos. % de cada venta convertida en caja libre.',
  'Conv. FCF': 'Conversión de FCF: flujo de caja libre ÷ beneficio neto. Mide la calidad del beneficio (1 = totalmente en efectivo).',
  'Rot. activos': 'Rotación de activos: ingresos ÷ activos totales. Cuántas veces convierte los activos en ventas. Mayor = más eficiente.',
  'Rot. inv.': 'Rotación de inventario: COGS ÷ inventario. Veces que se renueva el stock en un año.',
  'DSO': 'Days Sales Outstanding: días de media que tarda en cobrar a sus clientes = cuentas a cobrar ÷ ingresos × 365.',
  'DPO': 'Days Payable Outstanding: días de media que tarda en pagar a sus proveedores = cuentas a pagar ÷ COGS × 365.',
  'CCC': 'Cash Conversion Cycle: DIO + DSO - DPO. Días entre pagar inventario y cobrar ventas. Menor = mejor gestión del circulante.',
  'Apalanc.': 'Multiplicador de apalancamiento: activos ÷ fondos propios. Parte de la rentabilidad (DuPont) que viene de la deuda.',
  'Beta': 'Sensibilidad de la acción al mercado. Beta < 1 = menos volátil (defensiva); beta > 1 amplifica los movimientos del mercado.',
  'P/E Fwd': 'Forward P/E: precio ÷ beneficio por acción estimado para los próximos 12 meses. Adelanta el PER usando estimaciones de analistas.',
  'P. Objetivo': 'Precio objetivo medio de los analistas: valor que el consenso de analistas estima para la acción a 12 meses.',
  'Rec. analistas': 'Recomendación media de los analistas (1 = compra fuerte, 5 = venta fuerte) y número de analistas que la cubren.',
  'Dividend Rate': 'Dividendo anual por acción según Yahoo, en la divisa de la empresa.',
};
