export const ABBREVIATIONS: Record<string, string> = {
  'P/E': 'Precio / Beneficio: cuánto pagas por cada $1 de beneficio. Bajo = barato; alto = expectativas de crecimiento.',
  'P/B': 'Precio / Valor en libros: compara el precio con el patrimonio neto por acción. 1x = compras a precio de libros.',
  'P/S': 'Precio / Ventas: cuánto paga el mercado por cada $1 de ingresos. Útil para empresas sin beneficios.',
  'EV': 'Enterprise Value (valor de empresa): capitalización bursátil + deuda neta. Valor total de la empresa.',
  'EV/EBITDA': 'Valor de empresa / beneficio operativo antes de amortizaciones. Menor = potencialmente más barato.',
  'EV/EBIT': 'Valor de empresa / beneficio operativo. Más conservador que EV/EBITDA porque no suma la depreciación.',
  'ROE': 'Retorno sobre el patrimonio: beneficio neto / capital de los accionistas. Mide la rentabilidad para el accionista.',
  'ROA': 'Retorno sobre los activos: beneficio neto / activos totales. Mide cuán eficiente es la empresa usando sus activos.',
  'ROIC': 'Retorno sobre el capital invertido: beneficio operativo / capital invertido. Mide si la empresa crea valor al reinvertir.',
  'Current Ratio': 'Ratio de liquidez: activos corrientes / pasivos corrientes. Mide si puede pagar sus deudas a corto plazo.',
  'Debt/Equity': 'Deuda / Patrimonio: apalancamiento. Alto = depende más de deuda para financiarse.',
  'Dividend Yield': 'Rendimiento por dividendo: dividendo anual / precio de la acción. Lo que te paga la empresa por tenerla.',
  'Altman Z-Score': 'Indicador de riesgo de quiebra. Z > 3 = sana; Z < 1.8 = riesgo elevado de bancarrota.',
  'Piotroski': 'Puntuación de fortaleza financiera (0-9). Suma señales de rentabilidad, apalancamiento y eficiencia.',
  'DCF': 'Flujo de Caja Descontado: estima el valor proyectando los flujos de caja futuros y descontándolos al presente.',
  'PER': 'Precio / Beneficio (P/E). Cuánto pagas por cada unidad de beneficio. Método más usado por inversores.',
  'DDM': 'Descuento de Dividendos: valora la acción como la suma de sus dividendos futuros descontados.',
  'FCF Yield': 'Flujo de caja libre como % del precio de mercado. Mayor = genera más efectivo relativo a su precio.',
  'NCAV': 'Net Current Asset Value: activos corrientes ajustados menos deuda. Valor de liquidación de Graham.',
  'Graham': 'Número de Graham: tope defensivo de precio basado en beneficio y patrimonio. Por debajo = ganga segura.',
  'EBIT': 'Beneficio antes de intereses e impuestos. Mide el resultado de la operación pura.',
  'EBITDA': 'Beneficio antes de intereses, impuestos, depreciación y amortización. Mide la generación operativa de caja.',
  'EPS': 'Earnings Per Share: beneficio neto dividido entre las acciones. Beneficio por acción.',
  'BVPS': 'Book Value Per Share: patrimonio neto dividido entre las acciones. Valor contable por acción.',
  'FCF': 'Free Cash Flow: efectivo generado después de pagar gastos e inversión (CapEx). Caja realmente libre.',
  'CapEx': 'Capital Expenditures: inversión en activos fijos (fábricas, equipos, tecnología). Reinversión para crecer.',
  'SGA': 'Selling, General & Administrative: gastos comerciales y administrativos.',
  'I+D': 'Investigación y Desarrollo: gasto en innovación de productos y tecnología.',
  'COGS': 'Cost of Goods Sold: costo directo de producir los bienes o servicios vendidos.',
  'Goodwill': 'Fondo de comercio: prima pagada al comprar otra empresa por encima del valor de sus activos.',
  'Market Cap': 'Capitalización bursátil: precio de la acción × acciones en circulación. Valor de mercado de la empresa.',
  'TTM': 'Trailing Twelve Months: últimos 12 meses acumulados. Suma de los 4 trimestres más recientes.',
};
